### ISSUE TITLE
Discord guild link is expired/broken

### ISSUE THREAD

**Issue by elenakrittik** [CaedenPH/JesterBot#15]
**Is your feature request related to a problem? Please describe.**
The Discord guild link in CONTRIBUTING.md is expired/broken

**Describe the solution you'd like**
Replace old link with a fresh one

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CaedenPH** [comment]
> **Is your feature request related to a problem? Please describe.** The Discord guild link in CONTRIBUTING.md is expired/broken
> 
> **Describe the solution you'd like** Replace old link with a fresh one
> 
> **Describe alternatives you've considered** N/A
> 
> **Additional context** N/A

Thank you for the issue, I will replace the url with a new one.

**Comment by CaedenPH** [comment]
Fixed in https://github.com/CaedenPH/JesterBot/commit/f257d729157436cf4ace7a30699cb1d24ee4f646
